name: cc98_ocean
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  fluentui_system_icons: ^1.1.273
  riverpod: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  sidebarx: ^0.17.2
  html2md: ^1.3.2
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  flutter_svg: ^2.0.7 
  markdown_widget: ^2.3.2+8
  flutter_bbcode: ^1.5.1
  url_launcher: ^6.1.11
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0 
  flutter:
    sdk: flutter

  provider: ^6.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  bbob_dart: ^0.2.2-dev.1
  audioplayers: ^6.5.0
  flutter_riverpod: ^3.0.0
  pointycastle: ^4.0.0
  xml: ^6.6.1
  flutter_native_splash: ^2.4.7
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/emoji/
    - assets/images/emoji/ac-white/
    - assets/images/emoji/CC98/
    - assets/images/emoji/em/
    - assets/images/emoji/ms/
    - assets/images/emoji/tb/

flutter_native_splash:
  color: "#FFFFFF"                    # 背景色
  image: "assets/images/cc98.png"   # 居中图标
  android: true
  ios: true
  android_12:                         # Android 12+ 专用，图标会被裁成圆形
    image: "assets/images/cc98.png"
    icon_background_color: "#000000"



  